### ISSUE TITLE
implicit dependency to bootstrap

### ISSUE THREAD

**Issue by maxlath** [KyleNeedham/autocomplete#7]
hi! thank you for this project!

I just open an issue as I had troubles at first using it as the dependency to Bootstrap is only specified in a52bb74 commit message, probably explaining the errors I get with 

``` coffee
@ui.autocomplete.dropdown 'toggle'
```

and the events

```
'shown.bs.dropdown': 'setDropdownShown'
'hidden.bs.dropdown': 'setDropdownHidden'
```

which I guess aren't fired.

I don't know if you are still maintaining this project, but I thought it might a useful information for other people arriving here

**Comment by KyleNeedham** [comment]
Hey @maxlath, thanks for bringing that to my attention I have added a note to the readme to let people know that bootstrap is required. :+1:
